#!/usr/bin/env bash
# install nginx

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sudo ufw allow 'Nginx HTTP'

sed -i '/listen 80 default_server;/a \\tlisten [::]:80 default_server;' /etc/nginx/sites-available/default

service nginx start
