#!/usr/bin/env bash
# install nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i '/listen 80 default_server;/a \\tlisten [::]:80 default_server;' /etc/nginx/sites-available/default
service nginx restart
