#!/usr/bin/env bash
# install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
echo "server {
    listen 80;
    location / {
        return 200 'Hello World!';
        add_header Content-Type text/plain;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
