#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sed -i '/server_name _;/a \\trewrite ^/redirect_me$ https://github.com/drac-pro permanent;' /etc/nginx/sites-available/default

service nginx start
