#!/usr/bin/env bash
# installs and configures a load balancer on a server

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "frontend hbnb_frontend
	bind *:80
	mode http
	stats enable
        stats uri /haproxy?stats
        option forwardfor
	default_backend hbnb_backend

backend hbnb_backend
	balance roundrobin
	server 522745-web-01 52.4.1.57:80 check
	server 522745-web-02 52.3.244.12:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy reload
fi
