#!/usr/bin/env bash
# configures a server so that Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
sudo ufw allow 'Nginx HTTP'
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
