#!/usr/bin/env bash
#displays To infinity and beyond indefinitely With a sleep 2 in between each iteration
#displays I am invincible!!! when receiving a SIGTERM signal

while true
do
  trap 'echo "To infinity and beyond"' SIGTERM
  echo "To infinity and beyond"
  sleep 2
done
