#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# only display username, user id and Home directory path for the user

while read -r passwd; do
  echo "$passwd" | cut -d: -f1,3,6
done < "/etc/passwd"
