#!/usr/bin/env bash
#displays "Best School" 10 times using a while loop.

i=10
while [ $i -gt 0 ]
do
  if [ $i -eq 7 ]
  then
    echo "bad luck"
  elif [ $i -eq 3 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i-- ))
done
