#!/usr/bin/env bash
#displays the content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

dir=$PWD
for file in "$dir"/*
do
  name=${file##*/}
  name=${file#*-*}
  echo "$name"
done
