#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

docker run --add-host="localhost:127.0.0.2" --add-host="facebook.com:8.8.8.8"
